-- ════════════════════════════════════════════════════════════════════
-- PRUEBA D4 · CARRIL A
--
-- ⚠️ ESTE ARCHIVO NO SE PEGA EN EL EDITOR DE SQL. Es la ENTRADA de
--    pg_pruebas.py, que le pone el sobre (begin / rollback) y, si el
--    carril es B, tambien la identidad. Por eso NO lleva begin, ni
--    rollback, ni un solo `set`: el SQL de entrada tiene PROHIBIDO todo
--    control de transaccion (begin, commit, rollback, savepoint) y toda
--    palabra que cambie quien corre (set, set_config, reset, call, do).
--    El sobre y la identidad son de la herramienta, nunca de la prueba.
--
-- CARRIL A · llave maestra, saltea la RLS. Prueba reglas de CONTENIDO.
--
-- EXTRAIDO POR CONTENIDO de CAMBIO_DEVOLUCIONES.sql (lineas 614-618 del original, al
-- 17-sep-2026). El numero de linea NO es la llave: el bloque se localizo
-- por su par begin/rollback y su encabezado, y despues se VERIFICO
-- reensamblandolo y comparandolo con el original caracter por caracter.
-- Es la leccion del 16-sep, cuando un `sed -n '141,476p'` entrego el
-- pedazo equivocado y se pego P0-a creyendo que era otra cosa.
-- sha256[12] del cuerpo: 414cac308c23
-- ════════════════════════════════════════════════════════════════════
-- D4 · ESPERADO: **ERROR** — `null value in column "pedido_id" violates not-null`.
--      ⚠️ ESTA PRUEBA SE INVIRTIO EL 16-sep. Hasta esa fecha era un CONTROL que
--      tenia que PASAR ("la devolucion suelta sigue entrando sin causa"), porque la
--      columna era nullable. Con la opcion A ya no: la suelta NO entra, y eso es lo
--      que hay que comprobar.
--      Se deja escrito el cambio porque una prueba que quedo midiendo lo contrario
--      de lo que se construyo es el modo de falla del 15-sep (P0-a "fallando" por
--      la escalera rota) y el de la 7a del 14-ago: da el resultado de otra cosa y
--      nadie lo nota.
  insert into ent_devolucion (fecha, cliente_id, cliente_nombre, creado_por)
  values (current_date, 999999, 'PRUEBA d4 suelta', 'prueba-d4');
  select 'D4 MAL: entro una devolucion sin pedido' as resultado;
